# Generated by Django 5.1.1 on 2024-09-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_advocate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='name',
            field=models.CharField(default='Default Name', max_length=500),
        ),
        migrations.AddField(
            model_name='advocate',
            name='profile_pic',
            field=models.CharField(default='Default Name', max_length=200),
        ),
        migrations.AddField(
            model_name='advocate',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='bio',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
