# Generated by Django 5.1.1 on 2024-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_advocate_name_advocate_profile_pic_advocate_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
